/** \mainpage My Personal Index Page
 *
 * \section intro_sec Introduction
 *
 * This is the introduction.
 *
 * \section install_sec Installation
 *
 * \subsection step1 Step 1: Opening the box
 *
 * etc...
 */

/**
 * @brief %game related functions and classes
 */
namespace Game {
    public:
        /**
         * enables / disables if keyboard inputs get propagated to the game
         *
         * @param enabled  flag indicating if the input should be allowed or not
         **/
        function AllowKeyInput(bool enabled) {}

        /**
         * enables / disables if mouse inputs get propagated to the game
         *
         * @param enabled  flag indicating if the input should be allowed or not
         */
        function AllowCameraInput(bool enabled) {}
}

/**
 * @brief functions that do not interfere with the game in any way but are commonly used by a multitude of scripts
 */
namespace Utility {
    public:
        /**
         * delays the execution of a function
         *
         * @param  func       the function that gets executed after the given timeout
         * @param  timeout    delay in milliseconds that the function will wait before execution
         * @param  arguments  [optional] table of arguments that get passed as function parameters
         *
         * @return \ref Utility.Timeout object related to the function
         */
        function SetTimeout(function func, int delay timeout = 0, table arguments = {}) {}

        /**
         * @brief timeouts generated by SetTimeout
         * @see SetTimeout
         */
        class Timeout {
            public:
                /**
                 * removes the given timeout object, so the "planned" function does not get executed
                 */
                void function clear() {}
        }
}